version: "3"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --locale=C
    env_file:
      - docker/db/.env
    ports:
      - "12345:5432"
    volumes:
      - "./docker/db/data:/var/lib/postgresql/data"
      - "./docker/db/initdb:/docker-entrypoint-initdb.d"