version: "3"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --locale=C
    ports:
      - "12345:5432"
    volumes:
      - "./db/data:/var/lib/postgresql/data"
      - "./db/initdb:/docker-entrypoint-initdb.d"